=== GoldLink21/Cells/autos.xsd
<!-- Verifies autos.xml -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Root element -->
    <xs:element name="autos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="auto" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- Auto element -->
    <xs:element name="auto">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="state" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="neighborhood">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Moore"/>
                        <xs:enumeration value="Neuman"/>
                        <xs:enumeration value="Plus"/>
                        <xs:enumeration value="Diag"/>
                        <xs:enumeration value="Hat"/>
                        <xs:enumeration value="BigX"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- State element -->
    <xs:element name="state">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ts" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="default" type="xs:string" use="required"/>
            <xs:attribute name="color" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9A-Fa-f]{6}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <!-- TS element -->
    <xs:element name="ts">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="to" type="xs:integer" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== GoldLink21/Cells/autos/new_autos.xml
<?xml version="1.1" standalone='no'?>
<!-- Testing ground for new autos -->
<autos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:noNamespaceSchemaLocation="autos.xsd">
    <!-- Almost seeds? -->
    <auto name="_qpy" neighborhood="Moore">
        <state name="0" color="4b5d05" default="0">
            <ts to="1">6!0</ts>
            <ts to="1">.5</ts>
        </state>
        <state name="1" color="c95814" default="0">
            <ts to="1">!75</ts>
            <ts to="1">16</ts>
        </state>
    </auto>

    <auto name="_qbc" neighborhood="BigX">
        <state name="0" color="da8787" default="0">
            <ts to="1">00</ts>
            <ts to="1">7.</ts>
        </state>
        <state name="1" color="8b8af0" default="0">
            <ts to="1">56</ts>
        </state>
    </auto>

    <auto name="_aiy" neighborhood="Hat">
        <state name="0" color="d9e1c2" default="0">
            <ts to="2">.01.0.</ts>
            <ts to="2">[01]..202</ts>
            <ts to="4">.0.0.2</ts>
        </state>
        <state name="1" color="b05c37" default="2">
            <ts to="4">[01]..10.</ts>
            <ts to="1">.01.[01]1</ts>
            <ts to="4">.112[01].</ts>
        </state>
        <state name="2" color="278469" default="2">
            <ts to="5">...0..</ts>
        </state>
        <state name="3" color="dd3647" default="0">
            <ts to="4">[0]2..12</ts>
        </state>
        <state name="4" color="6133d6" default="1">
        </state>
        <state name="5" color="cc87bd" default="0">
            <ts to="2">..[1]020</ts>
            <ts to="5">[2][2]...1</ts>
            <ts to="2">1[2]210[01]</ts>
        </state>
    </auto>
    <auto name="_axb" neighborhood="Neuman">
        <state name="0" color="3a5589" default="0">
            <ts to="2">6[01267][01257]</ts>
        </state>
        <state name="1" color="1601b9" default="0">
            <ts to="1">..6</ts>
        </state>
        <state name="2" color="8a86be" default="1">
            <ts to="2">[012457][01247][7]</ts>
        </state>
    </auto>

    <auto name="_adv" neighborhood="Plus">
        <state name="0" color="0117ec" default="0">
            <ts to="1">[23]...[013]2</ts>
        </state>
        <state name="1" color="0140a7" default="2">
            <ts to="0">.[012]..2[01]</ts>
        </state>
        <state name="2" color="4ee2ea" default="4">
            <ts to="5">[023]..[01].0</ts>
        </state>
        <state name="3" color="397cb5" default="2">
            <ts to="5">.0.[3].0</ts>
        </state>
        <state name="4" color="1c7db9" default="1">
            <ts to="0">.[013].013</ts>
        </state>
        <state name="5" color="d8da00" default="2">
            <ts to="3">02[01].[1]2</ts>
        </state>
    </auto>
<!-- ================================================= -->
 
<!-- ================================================= -->
</autos>

=== GoldLink21/Cells/autos.xml
<?xml version="1.1" standalone='no'?>
<autos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xsi:noNamespaceSchemaLocation="autos.xsd">
    <auto name="gol" neighborhood="Moore">
        <state name="dead" color="000000" default="0">
            <ts to="1">.3</ts>
        </state>
        <state name="alive" color="FFFFFF" default="0">
            <ts to="1">.[23]</ts>
        </state>
    </auto>
    <auto name="gol_neuman" neighborhood="Neuman">
        <state name="dead" color="000000" default="0">
            <ts to="1">.3</ts>
        </state>
        <state name="alive" color="FFFFFF" default="0">
            <ts to="1">.[23]</ts>
        </state>
    </auto>
    <auto name="gol_big_x" neighborhood="BigX">
        <state name="dead" color="000000" default="0">
            <ts to="1">.3</ts>
        </state>
        <state name="alive" color="FFFFFF" default="0">
            <ts to="1">.[23]</ts>
        </state>
    </auto>
    <auto name="wireworld" neighborhood="Moore">
        <state name="Nothing" color="000000" default="0"/>
        <state name="Head" color="0000FF" default="2" />
        <state name="Tail" color="FF0000" default="3" />
        <state name="Conduit" color="FFFF00" default="3">
            <ts to="1">.[12]..</ts>
        </state>
    </auto>
    <auto name="brians_brain" neighborhood="Moore">
        <state name="Dead" default="0" color="000000">
            <ts to="1">.2.</ts>
        </state>
        <state name="Alive" default="2" color="FFFFFF" />
        <state name="Dying" default="0" color="0000FF" />
    </auto>
    <auto name="day_and_night" neighborhood="Moore">
        <state name="Dead" default="0" color="000000">
            <ts to="1">.[368]</ts>
        </state>
        <state name="Alive" default="1" color="FFFF00">
            <ts to="0">.[0125]</ts>
        </state>
    </auto>
    <auto name="seeds" neighborhood="Moore">
        <state name="Dead" default="0" color="000000">
            <ts to="1">.2</ts>
        </state>
        <state name="Alive" default="0" color="00FF00" />
    </auto>
    <auto name="gol_and_d" neighborhood="Moore">
        <state name="Dead" default="0" color="000000">
            <ts to="1">.3.</ts>
        </state>
        <state name="Alive" default="1" color="FFFFFF">
            <ts to="2">.[0145678].</ts>
        </state>
        <state name="Dying" default="0" color="0000FF" />
    </auto>
    <auto name="soldier" neighborhood="Moore">
        <state name="Nothing" default="0" color="000000">
            <ts to="1">.20..</ts>
            <ts to="2">.02..</ts>
        </state>
        <state name="Red" default="0" color="FF0000">
            <ts to="3">v5....</ts>
        </state>
        <state name="Blue" default="0" color="0000FF">
            <ts to="3">v5....</ts>
        </state>
        <state name="Dead" default="3" color="a0a0a0">
            <ts to="0">...4.</ts>
        </state>
        <state name="Wall" default="4" color="FFFFFF" />
    </auto>
    <auto name="path" neighborhood="Moore">
        <state name="Nothing" default="0" color="00FF00">
            <ts to="2">.^00.</ts>
            <ts to="3">..^0.</ts>
        </state>
        <state name="Path Center" default="1" color="7A2700" />
        <state name="Path Edge" default="2" color="7F6A4F">
            <ts to="0">.0..</ts>
        </state>
        <state name="Path Outer Wall" default="3" color="828282">
            <ts to="2">.^0..</ts>
            <ts to="0">..0.</ts>
        </state>
    </auto>
    <auto name="test" neighborhood="Plus">
        <state name="0" default="0" color="000000"></state>
        <state name="1" default="0" color="FFFFFF">
            <ts to="1">3.</ts>
        </state>
    </auto>
</autos>
